<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gmk_bookstore"
 *
 * Auto generated by Extension Builder 2013-01-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Text Renderer',
	'description' => 'Alternative for TYPO3 GIFBUILDER TEXT Rendering Processor',
	'category' => 'plugin',
	'author' => 'Oliver Hader',
	'author_email' => 'oliver.hader@typo3.org',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>